name: stagexl_bitmapfont
version: 0.5.2
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  xml: '>=4.5.1 <5.0.0'
  stagexl: '>=1.4.6 <2.0.0'

dev_dependencies:
  pedantic: any
  build_test: any
  build_runner: any
  build_web_compilers: any
