name: stagexl_bitmapfont
version: 0.4.0
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  xml: any
  browser: any
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: texture-formats

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
