name: stagexl_bitmapfont
version: 0.3.1
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  xml: any
  browser: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
