name: stagexl_bitmapfont
version: 0.5.0+1
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  xml: ^5.3.0
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: dart-2

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
