name: stagexl_bitmapfont
version: 0.5.0+1
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  stagexl:
    git:
      url: https://github.com/bp74/StageXL
      ref: non-nullable

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
