name: stagexl_bitmapfont
version: 0.5.0+1
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: dart-2-nnbd

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
