name: stagexl_bitmapfont
version: 0.1.0
author: Bernhard Pichler <support@stagexl.org>
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.11.0 <0.12.0'
dependency_overrides:
  stagexl:
    path: D:\GitHub\bp74\StageXL